# Generated by Django 4.0.4 on 2022-05-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_alter_product_options_product_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
    ]
