# Generated by Django 4.0.4 on 2022-05-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
