# Generated by Django 4.0.4 on 2022-06-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_shippingaddress_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
