# Generated by Django 4.0.4 on 2022-06-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cart',
        ),
    ]
