# Generated by Django 4.0.4 on 2022-06-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_shippingaddress_cart_shippingaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='name',
        ),
    ]
