# Generated by Django 4.0.4 on 2022-06-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_shippingaddress_address_shippingaddress_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
