# Generated by Django 4.0.4 on 2022-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_shippingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='adresse',
            field=models.ManyToManyField(to='store.shippingaddress'),
        ),
    ]
