# Generated by Django 4.0.4 on 2022-06-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_shippingaddress_cart_order_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adresse',
        ),
        migrations.AddField(
            model_name='order',
            name='adresse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress'),
            preserve_default=False,
        ),
    ]
