# Generated by Django 4.0.4 on 2022-06-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_order_adresse_order_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adresse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress'),
        ),
    ]
