# Generated by Django 4.0.4 on 2022-06-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_order_adresse_order_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adresse',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
            preserve_default=False,
        ),
    ]
