# Generated by Django 4.0.4 on 2022-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_shippingaddress_order_shippingaddress_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='cart',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='items',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
