# Generated by Django 4.0.4 on 2022-06-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteur',
            name='address',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
