# Generated by Django 4.0.4 on 2022-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_visiteur_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteur',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
