# Generated by Django 4.0.4 on 2022-06-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_visiteur_city_visiteur_state_visiteur_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteur',
            name='name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
