# Generated by Django 4.0.4 on 2022-06-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_visiteur_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiteur',
            name='city',
        ),
        migrations.RemoveField(
            model_name='visiteur',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visiteur',
            name='state',
        ),
        migrations.RemoveField(
            model_name='visiteur',
            name='zipcode',
        ),
    ]
